### ISSUE TITLE
Snapchat app 

### ISSUE THREAD

**Issue by mrhashishah** [AdguardTeam/AdGuardDNS#147]
When adguard dns is enabled on iOS app.
Snapchat app will not function as expected.
Turn on adguard dns > open Snapchat app > chat > start any conversation. There should be bottom left a blue dot or someone’s Bitmoji. As an indicator that the person you are chatting with is online and on the same conversation. That indicator is broken with adguard dns enabled.

**Comment by ameshkov** [comment]
Could you please check it again now? We've implemented some changes that I believe may have helped.

**Comment by mrhashishah** [comment]
It do works now thank you.

**Comment by Eugene-Savenko** [comment]
@ameshkov @Alex-302 The user claims that the issue has returned. Could you look into it again, please?

**Comment by Alex-302** [comment]
Cannot receive register SMS
![image](https://user-images.githubusercontent.com/8361299/120616508-f8cd2d80-c461-11eb-91d7-f2f953e9e649.png)

**Comment by Eugene-Savenko** [comment]
@Alex-302 Can someone please try again? The user (CRM ID 519215) claims the issue persists, and they want it to get sorted.

**Comment by Alex-302** [comment]
@Eugene-Savenko does it work with non filtered DNS without DNS filter?
